
package com.danielminami.memorygameshopify.model;

import javax.annotation.Generated;
import com.google.gson.annotations.SerializedName;

/**
 * This POJO was automaticaly generated by the component POJOs From JSON
 */

@Generated("net.hexar.json2pojo")
@SuppressWarnings("unused")
public class Variant {

    @SerializedName("admin_graphql_api_id")
    private String mAdminGraphqlApiId;
    @SerializedName("barcode")
    private Object mBarcode;
    @SerializedName("compare_at_price")
    private Object mCompareAtPrice;
    @SerializedName("created_at")
    private String mCreatedAt;
    @SerializedName("fulfillment_service")
    private String mFulfillmentService;
    @SerializedName("grams")
    private Long mGrams;
    @SerializedName("id")
    private Long mId;
    @SerializedName("image_id")
    private Object mImageId;
    @SerializedName("inventory_item_id")
    private Long mInventoryItemId;
    @SerializedName("inventory_management")
    private Object mInventoryManagement;
    @SerializedName("inventory_policy")
    private String mInventoryPolicy;
    @SerializedName("inventory_quantity")
    private Long mInventoryQuantity;
    @SerializedName("old_inventory_quantity")
    private Long mOldInventoryQuantity;
    @SerializedName("option1")
    private String mOption1;
    @SerializedName("option2")
    private Object mOption2;
    @SerializedName("option3")
    private Object mOption3;
    @SerializedName("position")
    private Long mPosition;
    @SerializedName("price")
    private String mPrice;
    @SerializedName("product_id")
    private Long mProductId;
    @SerializedName("requires_shipping")
    private Boolean mRequiresShipping;
    @SerializedName("sku")
    private String mSku;
    @SerializedName("taxable")
    private Boolean mTaxable;
    @SerializedName("title")
    private String mTitle;
    @SerializedName("updated_at")
    private String mUpdatedAt;
    @SerializedName("weight")
    private Double mWeight;
    @SerializedName("weight_unit")
    private String mWeightUnit;

    public String getAdminGraphqlApiId() {
        return mAdminGraphqlApiId;
    }

    public void setAdminGraphqlApiId(String adminGraphqlApiId) {
        mAdminGraphqlApiId = adminGraphqlApiId;
    }

    public Object getBarcode() {
        return mBarcode;
    }

    public void setBarcode(Object barcode) {
        mBarcode = barcode;
    }

    public Object getCompareAtPrice() {
        return mCompareAtPrice;
    }

    public void setCompareAtPrice(Object compareAtPrice) {
        mCompareAtPrice = compareAtPrice;
    }

    public String getCreatedAt() {
        return mCreatedAt;
    }

    public void setCreatedAt(String createdAt) {
        mCreatedAt = createdAt;
    }

    public String getFulfillmentService() {
        return mFulfillmentService;
    }

    public void setFulfillmentService(String fulfillmentService) {
        mFulfillmentService = fulfillmentService;
    }

    public Long getGrams() {
        return mGrams;
    }

    public void setGrams(Long grams) {
        mGrams = grams;
    }

    public Long getId() {
        return mId;
    }

    public void setId(Long id) {
        mId = id;
    }

    public Object getImageId() {
        return mImageId;
    }

    public void setImageId(Object imageId) {
        mImageId = imageId;
    }

    public Long getInventoryItemId() {
        return mInventoryItemId;
    }

    public void setInventoryItemId(Long inventoryItemId) {
        mInventoryItemId = inventoryItemId;
    }

    public Object getInventoryManagement() {
        return mInventoryManagement;
    }

    public void setInventoryManagement(Object inventoryManagement) {
        mInventoryManagement = inventoryManagement;
    }

    public String getInventoryPolicy() {
        return mInventoryPolicy;
    }

    public void setInventoryPolicy(String inventoryPolicy) {
        mInventoryPolicy = inventoryPolicy;
    }

    public Long getInventoryQuantity() {
        return mInventoryQuantity;
    }

    public void setInventoryQuantity(Long inventoryQuantity) {
        mInventoryQuantity = inventoryQuantity;
    }

    public Long getOldInventoryQuantity() {
        return mOldInventoryQuantity;
    }

    public void setOldInventoryQuantity(Long oldInventoryQuantity) {
        mOldInventoryQuantity = oldInventoryQuantity;
    }

    public String getOption1() {
        return mOption1;
    }

    public void setOption1(String option1) {
        mOption1 = option1;
    }

    public Object getOption2() {
        return mOption2;
    }

    public void setOption2(Object option2) {
        mOption2 = option2;
    }

    public Object getOption3() {
        return mOption3;
    }

    public void setOption3(Object option3) {
        mOption3 = option3;
    }

    public Long getPosition() {
        return mPosition;
    }

    public void setPosition(Long position) {
        mPosition = position;
    }

    public String getPrice() {
        return mPrice;
    }

    public void setPrice(String price) {
        mPrice = price;
    }

    public Long getProductId() {
        return mProductId;
    }

    public void setProductId(Long productId) {
        mProductId = productId;
    }

    public Boolean getRequiresShipping() {
        return mRequiresShipping;
    }

    public void setRequiresShipping(Boolean requiresShipping) {
        mRequiresShipping = requiresShipping;
    }

    public String getSku() {
        return mSku;
    }

    public void setSku(String sku) {
        mSku = sku;
    }

    public Boolean getTaxable() {
        return mTaxable;
    }

    public void setTaxable(Boolean taxable) {
        mTaxable = taxable;
    }

    public String getTitle() {
        return mTitle;
    }

    public void setTitle(String title) {
        mTitle = title;
    }

    public String getUpdatedAt() {
        return mUpdatedAt;
    }

    public void setUpdatedAt(String updatedAt) {
        mUpdatedAt = updatedAt;
    }

    public Double getWeight() {
        return mWeight;
    }

    public void setWeight(Double weight) {
        mWeight = weight;
    }

    public String getWeightUnit() {
        return mWeightUnit;
    }

    public void setWeightUnit(String weightUnit) {
        mWeightUnit = weightUnit;
    }

}
